# Generated by Django 3.0.8 on 2020-11-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200920_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='ngo_true',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
