# Generated by Django 3.0.8 on 2020-11-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productcategories_ngo_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ngo_true',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
